language: python
python:
  - "2.6"
  - "2.7"
install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install argparse unittest2; fi
  - pip install -r requirements.txt
script: python tests.py
